package aragon.mikesharp.model;

//import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 5/6/26, 3:12 PM from the specification file
 * <tt>file:/C:/Users/Julio/Desktop/ICO/6toICO/Compiladores/Compiladores/Parcial_2/Mis_pruebas/Mikesharp/jar/lexico.flex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\3\1\3\2\0\1\3\22\0\1\3\1\31\6\0\1\26"+
    "\1\27\1\30\1\30\1\25\1\21\1\4\1\30\12\1\1\22\1\24"+
    "\1\32\1\23\1\32\2\0\32\2\6\0\1\15\1\2\1\7\1\2"+
    "\1\12\1\11\2\2\1\5\2\2\1\16\1\17\1\6\1\10\2\2"+
    "\1\14\1\20\1\13\6\2\uff85\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    27,    54,    81,    27,   108,   135,   162,   189,   216, 
      243,    27,   270,    27,    27,    27,    27,    27,   297,   297, 
      324,   351,   378,   405,   432,   459,   486,   513,    27,   324, 
      540,   567,   594,   621,   648,   675,   702,   729,   756,   783, 
      810,   729,   837,   729,   864,   891,   918,   945,   972,   999, 
      999,  1026,   999,  1053,  1080,  1107,  1134,  1161,  1188,  1161, 
     1215,  1242,  1269,  1296,  1323,  1350,  1377,    27,  1404,  1431, 
       27
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\2\1\3\1\4\1\5\1\2\1\6\3\4\1\7"+
    "\1\10\1\4\1\11\2\4\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\14\1\23\1\24"+
    "\34\0\1\3\2\0\1\25\27\0\2\26\2\0\14\26"+
    "\13\0\2\26\2\0\1\26\1\27\12\26\13\0\2\26"+
    "\2\0\1\30\13\26\13\0\2\26\2\0\1\26\1\31"+
    "\12\26\13\0\2\26\2\0\5\26\1\32\6\26\13\0"+
    "\2\26\2\0\1\33\13\26\13\0\2\26\2\0\1\34"+
    "\13\26\35\0\1\35\32\0\1\16\10\0\1\36\32\0"+
    "\2\37\2\0\14\37\13\0\2\37\2\0\1\40\13\37"+
    "\13\0\2\37\2\0\1\37\1\41\12\37\13\0\2\37"+
    "\2\0\6\37\1\42\5\37\13\0\2\37\2\0\10\37"+
    "\1\43\3\37\13\0\2\37\2\0\5\37\1\44\6\37"+
    "\13\0\2\37\2\0\1\37\1\45\12\37\13\0\2\46"+
    "\2\0\14\46\13\0\2\46\2\0\2\46\1\47\11\46"+
    "\13\0\2\46\2\0\14\46\1\50\12\0\2\46\2\0"+
    "\5\46\1\51\6\46\13\0\2\46\2\0\11\46\1\52"+
    "\2\46\13\0\2\46\2\0\1\46\1\53\12\46\13\0"+
    "\2\46\2\0\3\46\1\54\10\46\13\0\2\55\2\0"+
    "\14\55\13\0\2\55\2\0\1\56\13\55\31\0\1\57"+
    "\14\0\2\55\2\0\7\55\1\60\4\55\13\0\2\55"+
    "\2\0\6\55\1\61\5\55\13\0\2\62\2\0\14\62"+
    "\13\0\2\62\2\0\3\62\1\63\10\62\17\0\1\64"+
    "\26\0\2\62\2\0\3\62\1\65\10\62\13\0\2\62"+
    "\2\0\7\62\1\66\4\62\13\0\2\67\2\0\14\67"+
    "\24\0\1\70\21\0\2\67\2\0\10\67\1\71\3\67"+
    "\13\0\2\72\2\0\14\72\20\0\1\73\25\0\2\72"+
    "\2\0\13\72\1\74\13\0\2\75\2\0\14\75\25\0"+
    "\1\76\20\0\2\77\2\0\14\77\26\0\1\100\17\0"+
    "\2\101\2\0\14\101\27\0\1\102\16\0\2\103\2\0"+
    "\14\103\32\0\1\104\13\0\2\105\2\0\14\105\13\0"+
    "\2\106\2\0\14\106\13\0\2\107\2\0\14\107\12\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  9,  1,  1,  9,  1,  1,  1,  1,  1,  1,  9,  1,  9,  9,  9, 
     9,  9,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  9,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  0,  1, 
     1,  1,  1,  0,  1,  1,  1,  0,  1,  1,  0,  1,  1,  0,  1,  0, 
     1,  0,  1,  9,  1,  1,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[1458];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 90) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 

   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token

   */
  public int yylex() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 67: 
          {  System.out.println("Token: finmientras | Lexema: " + yytext());  }
        case 72: break;
        case 28: 
          {  System.out.println("Token: := | Lexema: " + yytext());  }
        case 73: break;
        case 3: 
        case 5: 
        case 6: 
        case 7: 
        case 8: 
        case 9: 
        case 10: 
        case 21: 
        case 22: 
        case 23: 
        case 24: 
        case 25: 
        case 26: 
        case 30: 
        case 31: 
        case 33: 
        case 34: 
        case 35: 
        case 36: 
        case 37: 
        case 38: 
        case 40: 
        case 42: 
        case 44: 
        case 45: 
        case 47: 
        case 48: 
        case 49: 
        case 53: 
        case 54: 
        case 56: 
        case 57: 
        case 60: 
        case 62: 
        case 64: 
        case 66: 
        case 68: 
        case 69: 
        case 70: 
          {  System.out.println("Token: identificador | Lexema: " + yytext());  }
        case 74: break;
        case 43: 
          {  System.out.println("Token: sino | Lexema: " + yytext());  }
        case 75: break;
        case 50: 
          {  System.out.println("Token: inicio | Lexema: " + yytext());  }
        case 76: break;
        case 32: 
          {  System.out.println("Token: fin | Lexema: " + yytext());  }
        case 77: break;
        case 1: 
        case 12: 
        case 18: 
          {  System.err.println("Error Léxico: Carácter no reconocido '" + yytext() + "' en línea " + (yyline+1) + ", columna " + (yycolumn+1));  }
        case 78: break;
        case 41: 
          {  System.out.println("Token: real | Lexema: " + yytext());  }
        case 79: break;
        case 11: 
          {  System.out.println("Token: operadores | Lexema: " + yytext());  }
        case 80: break;
        case 15: 
          {  System.out.println("Token: , | Lexema: " + yytext());  }
        case 81: break;
        case 14: 
          {  System.out.println("Token: ; | Lexema: " + yytext());  }
        case 82: break;
        case 16: 
          {  System.out.println("Token: ( | Lexema: " + yytext());  }
        case 83: break;
        case 17: 
          {  System.out.println("Token: ) | Lexema: " + yytext());  }
        case 84: break;
        case 52: 
          {  System.out.println("Token: entero | Lexema: " + yytext());  }
        case 85: break;
        case 27: 
          {  System.out.println("Token: si | Lexema: " + yytext());  }
        case 86: break;
        case 13: 
        case 19: 
          {  System.out.println("Token: comparaciones | Lexema: " + yytext());  }
        case 87: break;
        case 4: 
          {  /* Ignorar */  }
        case 88: break;
        case 59: 
          {  System.out.println("Token: mientras | Lexema: " + yytext());  }
        case 89: break;
        case 2: 
        case 29: 
          {  System.out.println("Token: numero | Lexema: " + yytext());  }
        case 90: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            return YYEOF;
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, i.e. it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
//  public static void main(String argv[]) {
//    if (argv.length == 0) {
//      System.out.println("Usage : java Lexer <inputfile>");
//    }
//    else {
//      for (int i = 0; i < argv.length; i++) {
//        Lexer scanner = null;
//        try {
//          scanner = new Lexer( new java.io.FileReader(argv[i]) );
//          while ( !scanner.yy_atEOF ) scanner.yylex();
//        }
//        catch (java.io.FileNotFoundException e) {
//          System.out.println("File not found : \""+argv[i]+"\"");
//        }
//        catch (java.io.IOException e) {
//          System.out.println("IO error scanning file \""+argv[i]+"\"");
//          System.out.println(e);
//        }
//        catch (Exception e) {
//          System.out.println("Unexpected exception:");
//          e.printStackTrace();
//        }
//      }
//    }
//  }


}
