
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 06 20:17:51 CST 2026
//----------------------------------------------------

package fes.aragon.tablerointerprete.analizador;

import fes.aragon.tablerointerprete.modelo.*;
import java_cup.runtime.*;

import java.util.ArrayList;
import java.util.List;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed May 06 20:17:51 CST 2026
  */
public class AnalizadorSintactico extends lr_parser {

  /** Default constructor. */
  public AnalizadorSintactico() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintactico(Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintactico(Scanner s, SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\017\000\002\002\004\000\002\002\007\000\002\003" +
    "\003\000\002\003\004\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\004\000\002" +
    "\007\005\000\002\006\010\000\002\012\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\035\000\004\004\005\001\002\000\004\002\037\001" +
    "\002\000\004\015\006\001\002\000\004\015\007\001\002" +
    "\000\020\006\013\007\010\010\015\011\020\012\021\013" +
    "\023\016\022\001\002\000\024\005\ufff9\006\ufff9\007\ufff9" +
    "\010\ufff9\011\ufff9\012\ufff9\013\ufff9\014\ufff9\016\ufff9\001" +
    "\002\000\024\005\ufffc\006\ufffc\007\ufffc\010\ufffc\011\ufffc" +
    "\012\ufffc\013\ufffc\014\ufffc\016\ufffc\001\002\000\024\005" +
    "\ufffd\006\ufffd\007\ufffd\010\ufffd\011\ufffd\012\ufffd\013\ufffd" +
    "\014\ufffd\016\ufffd\001\002\000\024\005\ufffa\006\ufffa\007" +
    "\ufffa\010\ufffa\011\ufffa\012\ufffa\013\ufffa\014\ufffa\016\ufffa" +
    "\001\002\000\022\005\036\006\013\007\010\010\015\011" +
    "\020\012\021\013\023\016\022\001\002\000\024\005\ufff8" +
    "\006\ufff8\007\ufff8\010\ufff8\011\ufff8\012\ufff8\013\ufff8\014" +
    "\ufff8\016\ufff8\001\002\000\024\005\uffff\006\uffff\007\uffff" +
    "\010\uffff\011\uffff\012\uffff\013\uffff\014\uffff\016\uffff\001" +
    "\002\000\024\005\ufffb\006\ufffb\007\ufffb\010\ufffb\011\ufffb" +
    "\012\ufffb\013\ufffb\014\ufffb\016\ufffb\001\002\000\024\005" +
    "\ufff7\006\ufff7\007\ufff7\010\ufff7\011\ufff7\012\ufff7\013\ufff7" +
    "\014\ufff7\016\ufff7\001\002\000\004\015\035\001\002\000" +
    "\004\020\033\001\002\000\020\006\013\007\010\010\015" +
    "\011\020\012\021\013\023\016\022\001\002\000\004\014" +
    "\027\001\002\000\022\006\013\007\010\010\015\011\020" +
    "\012\021\013\023\014\ufff3\016\022\001\002\000\024\005" +
    "\ufffe\006\ufffe\007\ufffe\010\ufffe\011\ufffe\012\ufffe\013\ufffe" +
    "\014\ufffe\016\ufffe\001\002\000\004\016\030\001\002\000" +
    "\004\020\031\001\002\000\004\015\032\001\002\000\024" +
    "\005\ufff4\006\ufff4\007\ufff4\010\ufff4\011\ufff4\012\ufff4\013" +
    "\ufff4\014\ufff4\016\ufff4\001\002\000\004\015\034\001\002" +
    "\000\024\005\ufff5\006\ufff5\007\ufff5\010\ufff5\011\ufff5\012" +
    "\ufff5\013\ufff5\014\ufff5\016\ufff5\001\002\000\024\005\ufff6" +
    "\006\ufff6\007\ufff6\010\ufff6\011\ufff6\012\ufff6\013\ufff6\014" +
    "\ufff6\016\ufff6\001\002\000\004\002\000\001\002\000\004" +
    "\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\035\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\014\003\013\004\015" +
    "\005\011\006\010\007\016\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\004\025\005\011\006\010\007\016\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\003\024\004" +
    "\015\005\011\006\010\007\016\012\023\001\001\000\002" +
    "\001\001\000\012\004\025\005\011\006\010\007\016\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public Symbol do_action(
    int                        act_num,
    lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private List<Instruccion> instrucciones = new ArrayList<>();
    private List<String> codigoIntermedio = new ArrayList<>();
    public int posicionXInicio = 1;
    public int posicionYInicio = 1;
    
    public List<Instruccion> getInstrucciones() {
        return instrucciones;
    }
    
    public List<String> getCodigoIntermedio() {
        return codigoIntermedio;
    }
    
    public int getPosicionXInicio() {
        return posicionXInicio;
    }
    
    public int getPosicionYInicio() {
        return posicionYInicio;
    }
    
    public void agregarInstruccion(Instruccion inst) {
        instrucciones.add(inst);
        codigoIntermedio.add(inst.toIntermediateCode());
    }
    
    public void agregarInstruccion(String codIntermedio, Instruccion inst) {
        if (inst != null) {
            instrucciones.add(inst);
        }
        codigoIntermedio.add(codIntermedio);
    }
    
    public void reiniciar() {
        instrucciones.clear();
        codigoIntermedio.clear();
    }
    
    public void error(String message) {
        System.err.println("Error sintáctico: " + message);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintactico$actions {
  private final AnalizadorSintactico parser;

  /** Constructor */
  CUP$AnalizadorSintactico$actions(AnalizadorSintactico parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final Symbol CUP$AnalizadorSintactico$do_action(
    int                        CUP$AnalizadorSintactico$act_num,
    lr_parser CUP$AnalizadorSintactico$parser,
    java.util.Stack            CUP$AnalizadorSintactico$stack,
    int                        CUP$AnalizadorSintactico$top)
    throws Exception
    {
      /* Symbol object for return from actions */
      Symbol CUP$AnalizadorSintactico$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // bloque ::= instrucciones 
            {
              List<Instruccion> RESULT =null;
		int instsleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int instsright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		List<Instruccion> insts = (List<Instruccion>)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = insts; 
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("bloque",8, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // repeticion ::= REPITE bloque HASTA IDENTIFICADOR IGUAL ENTERO 
            {
              Instruccion RESULT =null;
		int bloqleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).left;
		int bloqright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).right;
		List<Instruccion> bloq = (List<Instruccion>)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).value;
		int varleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int varright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		String var = (String)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int numleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int numright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Integer num = (Integer)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
        // El ciclo NO tiene variable en la línea de repite
        // La variable está solo en la línea "hasta"
        // Usamos "temp" como variable temporal y 1 como inicio por defecto
        Ciclo ciclo = new Ciclo(var, 1, bloq, var, num, 0, 0);
        parser.agregarInstruccion("REP [" + var + "=1.." + num + "]", ciclo);
        RESULT = ciclo;
    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("repeticion",4, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // asignacion ::= IDENTIFICADOR IGUAL ENTERO 
            {
              Instruccion RESULT =null;
		int varleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int varright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		String var = (String)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int numleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int numright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Integer num = (Integer)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
        // Crear instrucción de asignación
        InstruccionAsignacion inst = new InstruccionAsignacion(var, num, 0, 0);
        parser.agregarInstruccion("SET " + var + " = " + num, inst);
        RESULT = inst;
    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("asignacion",5, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // movimiento ::= MOVER ENTERO 
            {
              Instruccion RESULT =null;
		int pasosleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int pasosright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Integer pasos = (Integer)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
        Instruccion inst = new InstruccionMover(pasos, 0, 0);
        parser.agregarInstruccion("MV " + pasos, inst);
        RESULT = inst;
    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("movimiento",3, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // movimiento ::= DERECHA 
            {
              Instruccion RESULT =null;
		
        Instruccion inst = new InstruccionMovimiento("derecha", 0, 0);
        parser.agregarInstruccion("DER", inst);
        RESULT = inst;
    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("movimiento",3, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // movimiento ::= IZQUIERDA 
            {
              Instruccion RESULT =null;
		
        Instruccion inst = new InstruccionMovimiento("izquierda", 0, 0);
        parser.agregarInstruccion("IZQ", inst);
        RESULT = inst;
    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("movimiento",3, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // movimiento ::= ABAJO 
            {
              Instruccion RESULT =null;
		
        Instruccion inst = new InstruccionMovimiento("abajo", 0, 0);
        parser.agregarInstruccion("ABA", inst);
        RESULT = inst;
    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("movimiento",3, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // movimiento ::= ARRIBA 
            {
              Instruccion RESULT =null;
		
        Instruccion inst = new InstruccionMovimiento("arriba", 0, 0);
        parser.agregarInstruccion("ARR", inst);
        RESULT = inst;
    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("movimiento",3, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= asignacion 
            {
              Instruccion RESULT =null;
		int asigleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int asigright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Instruccion asig = (Instruccion)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = asig; 
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= repeticion 
            {
              Instruccion RESULT =null;
		int repleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int repright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Instruccion rep = (Instruccion)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = rep; 
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion ::= movimiento 
            {
              Instruccion RESULT =null;
		int movleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int movright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Instruccion mov = (Instruccion)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = mov; 
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // instrucciones ::= instrucciones instruccion 
            {
              List<Instruccion> RESULT =null;
		int listaleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int listaright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		List<Instruccion> lista = (List<Instruccion>)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		int instleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int instright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Instruccion inst = (Instruccion)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
        lista.add(inst);
        RESULT = lista;
    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("instrucciones",1, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // instrucciones ::= instruccion 
            {
              List<Instruccion> RESULT =null;
		int instleft = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int instright = ((Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Instruccion inst = (Instruccion)((Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		
        List<Instruccion> lista = new ArrayList<>();
        lista.add(inst);
        RESULT = lista;
    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("instrucciones",1, ((Symbol)CUP$AnalizadorSintactico$stack.peek()), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= INICIO ENTERO ENTERO instrucciones FIN 
            {
              Object RESULT =null;
		int posXleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int posXright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		Integer posX = (Integer)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		int posYleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int posYright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		Integer posY = (Integer)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int instsleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int instsright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		List<Instruccion> insts = (List<Instruccion>)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		 
        parser.reiniciar();
        parser.posicionXInicio = posX;
        parser.posicionYInicio = posY;
        parser.agregarInstruccion("i " + posX + " " + posY, null);
        for(Instruccion inst : insts) {
            parser.agregarInstruccion(inst);
        }
        parser.agregarInstruccion("fn", null);
        System.out.println("Compilado. Inicio en: (" + posX + "," + posY + 
                          "). Instrucciones: " + insts.size());
    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int start_valright = ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object start_val = (Object)((Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintactico$parser.done_parsing();
          return CUP$AnalizadorSintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

