
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 06 20:17:51 CST 2026
//----------------------------------------------------

package fes.aragon.tablerointerprete.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 13;
  public static final int ABAJO = 5;
  public static final int ENTERO = 11;
  public static final int ARRIBA = 4;
  public static final int INICIO = 2;
  public static final int FIN = 3;
  public static final int EOF = 0;
  public static final int IZQUIERDA = 6;
  public static final int IGUAL = 14;
  public static final int error = 1;
  public static final int DERECHA = 7;
  public static final int HASTA = 10;
  public static final int MOVER = 8;
  public static final int IDENTIFICADOR = 12;
  public static final int REPITE = 9;
}

